- verify.py.in
Don't report vacuity error if there is a pass message for the same line.
This is needed because an sassert can be split because of jumpthreading.
This leads to one BB being reachable and the other one being unreachable.
In this case vacuity actually passed even though it is unreachable in the other instance.
> feat(script): supress spurious vacuity errors

- seahorn/jobs/string_new_from_string/sea.yaml
- seahorn/sea_vac.yaml
Also change string_from_new_string test to use smtfd tactic since seahorn hangs with default solver. Default solver uses smt solver and smtfd uses sat solver
> feat(vac): add sentinel branch check in vacuity mode

- seahorn/jobs/byte_cursor_compare_lookup/CMakeLists.txt
- seahorn/jobs/byte_cursor_compare_lookup/sea.yaml
- seahorn/jobs/byte_cursor_eq_c_str/CMakeLists.txt
- seahorn/jobs/byte_cursor_eq_c_str/sea.yaml
- seahorn/jobs/byte_cursor_eq_c_str_ignore_case/CMakeLists.txt
- seahorn/jobs/byte_cursor_eq_c_str_ignore_case/sea.yaml
- seahorn/jobs/byte_cursor_eq_ignore_case/CMakeLists.txt
- seahorn/jobs/byte_cursor_eq_ignore_case/sea.yaml
Set --bound=MAX_BUFFER_SIZE for cases failing backward assertions
during vacuity mode.
> fix(vac): add unroll bound for failing cases

- seahorn/include/linked_list_helper.h
- seahorn/jobs/linked_list_insert_after/CMakeLists.txt
- seahorn/jobs/linked_list_insert_after/aws_linked_list_insert_after_harness.c
- seahorn/jobs/linked_list_insert_before/CMakeLists.txt
- seahorn/jobs/linked_list_insert_before/aws_linked_list_insert_before_harness.c
- seahorn/jobs/linked_list_pop_back/aws_linked_list_pop_back_harness.c
- seahorn/jobs/linked_list_remove/CMakeLists.txt
- seahorn/jobs/linked_list_remove/aws_linked_list_remove_harness.c
- seahorn/jobs/linked_list_swap_contents/CMakeLists.txt
- seahorn/jobs/linked_list_swap_contents/aws_linked_list_swap_contents_harness.c
- seahorn/lib/linked_list_helper.c
- added helpers for nd aws linked lists with the form head <--> front --> nd...nd <-- back <--> tail
- `void sea_nd_init_aws_linked_list(struct aws_linked_list *list, size_t *length)` nd initializer function for the above form when length > 2
-  `void aws_linked_list_save_full(struct aws_linked_list *list, size_t size, struct aws_linked_list_node *start, struct aws_linked_list_node *end, struct saved_aws_linked_list *to_save)` function for saving to `saved_aws_linked_list` snapshot between nodes start and end; `saved_aws_linked_list.start` is not used because there is no need to save more than 1 level; if there is a need to go deeper, user should use `save_to_head` and `save_to_tail` instead.
- `bool is_aws_list_unchanged_full(struct aws_linked_list *list, struct saved_aws_linked_list …
> refactor(jobs): migrate remaining linked list jobs to nd helpers

- seahorn/jobs/array_list_swap/aws_array_list_swap_harness.c
passes verification except under cex mode with bv array mem model; useful for debugging a similar issue in priority_queue_s_swap  (also more meaningful verification).
> feat(job): add check for data swap in array_list_swap

- seahorn/jobs/priority_queue_clean_up/aws_priority_queue_clean_up_harness.c
there is undefined behaviour in `AWS_IS_ZEROED` causing cex mode to return sat.
> use utils `assert_all_zeroes` over `AWS_IS_ZEROED`

- seahorn/jobs/array_list_set_at/sea.yaml
- seahorn/jobs/byte_cursor_from_string/sea.yaml
`array_list_set_at` and `byte_cursor_from_string` are failing in cex with solver tactic set to `smtfd` https://github.com/seahorn/verify-c-common/runs/1532417861?check_suite_focus=true
use default tactic instead
> fix(jobs): remove smtfd tactics from jobs that are failing falsely

- .gitignore
- scripts/get_exper_res.py
Add a `python` script for running benchmarks. The `CSV` results will be stored inside the `data` folder.
> feat(scripts): add a python script for benchmark running

- scripts/get_loc_info.py
Add a python script to compute all lines of code info based on each harness that Seahorn analyzes.
The script work when you build all harnesses already.
You can set arg `--debug` to display detailed loc which computed based on each function call.
> feat(scripts): add computing line of code python script

- CMakeLists.txt
- scripts/get_exper_res.py
- fix read`.xml` attribute when the `execution time` tag is not the first one in tag `NamedMeasurement`.
- add args to python scripts to allow run Seahorn and Klee individually
> feat(scripts): add flags for running individual experiment

- seahorn/jobs/byte_cursor_left_trim_pred/CMakeLists.txt
- seahorn/jobs/byte_cursor_left_trim_pred/aws_byte_cursor_left_trim_pred_harness.c
- seahorn/jobs/byte_cursor_right_trim_pred/CMakeLists.txt
- seahorn/jobs/byte_cursor_right_trim_pred/aws_byte_cursor_right_trim_pred_harness.c
- seahorn/jobs/byte_cursor_satisfies_pred/CMakeLists.txt
- seahorn/jobs/byte_cursor_satisfies_pred/aws_byte_cursor_satisfies_pred_harness.c
- seahorn/jobs/byte_cursor_trim_pred/CMakeLists.txt
- seahorn/jobs/byte_cursor_trim_pred/aws_byte_cursor_trim_pred_harness.c
- seahorn/jobs/linked_list_pop_back/aws_linked_list_pop_back_harness.c
- seahorn/jobs/priority_queue_s_sift_either/CMakeLists.txt
- seahorn/jobs/priority_queue_s_sift_up/CMakeLists.txt
- seahorn/jobs/ptr_eq/CMakeLists.txt
- seahorn/jobs/ring_buffer_acquire/CMakeLists.txt
- seahorn/jobs/ring_buffer_acquire/aws_ring_buffer_acquire_harness.c
- seahorn/jobs/ring_buffer_acquire_up_to/CMakeLists.txt
- seahorn/jobs/ring_buffer_acquire_up_to/aws_ring_buffer_acquire_up_to_harness.c
- seahorn/jobs/ring_buffer_clean_up/CMakeLists.txt
- seahorn/jobs/ring_buffer_init/CMakeLists.txt
- seahorn/jobs/ring_buffer_init/aws_ring_buffer_init_harness.c
- seahorn/jobs/round_up_to_power_of_two/CMakeLists.txt
- seahorn/lib/CMakeLists.txt
- seahorn/lib/klee_byte_buf_helper.c
- seahorn/lib/klee_ring_buffer_helper.c
- add Klee works on calling uninterpreted predicate fn
- byte_cursor_left_trim_pred
- byte_cursor_right_trim_pred
- byte_cursor_satisfies_pred
- byte_cursor_trim_pred
- add missed assumption on linked list back harness
```
Start 15: klee_ptr_eq_test
1/1 Test #15: klee_ptr_eq_test .................   Passed    0.62 sec
Start 12: klee_round_up_to_power_of_two_test
1/1 Test #12: klee_round_up_to_power_of_two_test ...   Passed    0.65 sec
```
- add part of ring_buffer targets for klee
```
Start 258: klee_ring_buffer_clean_up_test
1/4 Test #258: klee_ring_buffer_clean_up_test ........   Passed   12.37 sec
Start 260: klee_ring_buffer_init_test
2/4 Test #260: klee_ring_buffer_init_test ............   Passed   13.45 sec
Start 281: klee_ring_buffer_acquire_test
3/4 Test #281: …
```
> Klee covers more harnesses

- seahorn/CMakeLists.txt
- seahorn/jobs/ring_buffer_buf_belongs_to_pool/CMakeLists.txt
- seahorn/jobs/ring_buffer_buf_belongs_to_pool/aws_ring_buffer_buf_belongs_to_pool_harness.c
- seahorn/jobs/ring_buffer_release/CMakeLists.txt
- seahorn/jobs/ring_buffer_release/aws_ring_buffer_release_harness.c
- seahorn/jobs/string_bytes/CMakeLists.txt
- seahorn/jobs/string_compare/CMakeLists.txt
- seahorn/jobs/string_destroy/CMakeLists.txt
- seahorn/jobs/string_destroy_secure/CMakeLists.txt
- seahorn/jobs/string_destroy_secure/aws_string_destroy_secure_harness.c
- seahorn/jobs/string_eq/CMakeLists.txt
- seahorn/jobs/string_eq_byte_buf/CMakeLists.txt
- seahorn/jobs/string_eq_byte_buf_ignore_case/CMakeLists.txt
- seahorn/jobs/string_eq_byte_cursor/CMakeLists.txt
- seahorn/jobs/string_eq_byte_cursor_ignore_case/CMakeLists.txt
- seahorn/jobs/string_eq_c_str/CMakeLists.txt
- seahorn/jobs/string_eq_c_str_ignore_case/CMakeLists.txt
- seahorn/jobs/string_eq_ignore_case/CMakeLists.txt
- seahorn/jobs/string_new_from_array/CMakeLists.txt
- seahorn/jobs/string_new_from_array/aws_string_new_from_array_harness.c
- seahorn/jobs/string_new_from_c_str/CMakeLists.txt
- seahorn/jobs/string_new_from_string/CMakeLists.txt
- seahorn/jobs/string_new_from_string/aws_string_new_from_string_harness.c
- seahorn/lib/klee_byte_buf_helper.c
- seahorn/lib/klee_ring_buffer_helper.c
- seahorn/lib/klee_string_helper.c
klee's running time on Ring Buffer:
```
Start 273: klee_ring_buffer_clean_up_test
1/6 Test #273: klee_ring_buffer_clean_up_test ..............   Passed   11.32 sec
Start 275: klee_ring_buffer_init_test
2/6 Test #275: klee_ring_buffer_init_test ..................   Passed   12.24 sec
Start 295: klee_ring_buffer_release_test
3/6 Test #295: klee_ring_buffer_release_test ...............   Passed   46.40 sec
Start 297: klee_ring_buffer_acquire_test
4/6 Test #297: klee_ring_buffer_acquire_test ...............   Passed   50.66 sec
Start 299: klee_ring_buffer_buf_belongs_to_pool_test
5/6 Test #299: klee_ring_buffer_buf_belongs_to_pool_test ...   Passed   43.59 sec
Start 301: klee_ring_buffer_acquire_up_to_test
6/6 Test #301: klee_ring_buffer_acquire_up_to_test .........   Passed   61.42 sec
``` …
> Klee tests cover ring buffer and string

- .github/workflows/fuzz.yml
- .gitignore
Current plan is to publish coverage html pages as a sub-section of this repository's github pages. 
Example fork page: http://danblitzhou.ca/verify-c-common/fuzzing_coverage/index.html
On each push to `master` branch, fuzzing build will run and create latest coverage html pages; the changes will be stored in `fuzzing_coverage/` directory and pushed to `gh-pages` branch of `verify-c-common` repo. Upon successful deployment, the coverage pages should be updated.
> feat(CI): fuzz CI step to deploy coverage html

- seahorn/jobs/array_list_pop_front/CMakeLists.txt
- seahorn/jobs/array_list_pop_front/sea.yaml
Add `sea.yaml` file to configure word size to fix the following error:
```
Error: unsupported memcpy due to size and/or alignment.
Warning: Interpreting memcpy as noop
```
> fix(jobs): add word size one config for memcpy

- scripts/get_exper_res.py
Updated `get_exper_res.py` script such that experimenters can use any combination of `sea` flags when running the script to batch collect data.
Example usage: `python3 ../scripts/get_exper_res.py --seahorn --horn-bmc-solver=smt-y2 --horn-bv2-lambdas=false --timeout=600`
yes, user can also set timeout for ctest per job
Some example data can also be found [in this repo](https://github.com/danblitzhou/sea-bmc-datadump) as a makeshift solution
> feat(scripts): custom flags for experiment data script

- CMakeLists.txt
- seahorn/CMakeLists.txt
- seahorn/lib/bcmp.c
LLVM rewrites memcpy and memmove using its own intrinsics. SeaHorn assumes that
intrinsics are safe and does not check them for memory. It is assumed that
conversion to intrinsics will add memory checks (which does happen on some
platforms).
This commit achieves two things
1. add clang options to no automatically lift memcpy/memmove into intrisics
2. add our implementation of memcpy/memmove that check memory safety and then
call intrinsics directly
The behaviour is controlled by the cmake option SEA_LLVM_MEM_BUILTINS
The default configuration is OFF that enables safety checks.
> feat(lib): safety checks on memcpy and memmove

- seahorn/jobs/priority_queue_pop/CMakeLists.txt
- seahorn/jobs/priority_queue_push/CMakeLists.txt
- seahorn/jobs/priority_queue_push_ref/CMakeLists.txt
- seahorn/jobs/priority_queue_remove/CMakeLists.txt
- seahorn/jobs/priority_queue_s_sift_down/CMakeLists.txt
- seahorn/jobs/priority_queue_s_sift_either/CMakeLists.txt
- seahorn/jobs/priority_queue_s_sift_up/CMakeLists.txt
- seahorn/jobs/priority_queue_s_swap/CMakeLists.txt
- externalize static function for priority queue functions started with `s_*`.
```
1/15 Test #289: klee_priority_queue_init_static_test .....   Passed   40.96 sec
2/15 Test #291: klee_priority_queue_init_dynamic_test ....   Passed   41.69 sec
3/15 Test #287: klee_priority_queue_top_test .............   Passed   88.73 sec
4/15 Test #293: klee_priority_queue_clean_up_test ........   Passed   89.06 sec
5/15 Test #285: klee_priority_queue_capacity_test ........   Passed  101.13 sec
6/15 Test #283: klee_priority_queue_size_test ............   Passed  101.64 sec
7/15 Test #300: klee_priority_queue_s_swap_test ..........   Passed  110.74 sec
8/15 Test #302: klee_priority_queue_s_sift_up_test .......   Passed  111.85 sec
9/15 Test #306: klee_priority_queue_s_sift_either_test ...   Passed   88.34 …
```
> fix(jobs): externalize static functions for klee

- docker/verify-c-common-fuzz.Dockerfile
- docker/verify-c-common-klee.Dockerfile
- docker/verify-c-common-smack.Dockerfile
- docker/verify-c-common.Dockerfile
Fixed the issue caused by adding Kitware APT Repository. Use an alternative way to install the latest CMake (version `3.21.3`).
> fix(docker): update commands to install lastest cmake

- seahorn/jobs/hash_table_clean_up/aws_hash_table_clean_up_harness.c
- seahorn/jobs/hash_table_foreach/aws_hash_table_foreach_harness.c
- seahorn/lib/fuzz_hash_table_helper.c
- seahorn/lib/nd_fuzz.c
Havoc after malloc must have opened up a lot more interesting execution paths, thus exposing some mistakes overlooked during creating the fuzzing tests.
Tested all fuzzing tests locally.
> fix(fuzzing): UAF and hash entry count

- .github/workflows/klee.yml
- docker/verify-c-common-klee.Dockerfile
- docker/verify-c-common.Dockerfile
- seahorn/jobs/array_list_sort/aws_array_list_sort_harness.c
- seahorn/jobs/hash_table_eq/CMakeLists.txt
1. Resolve KLEE failing and timeout tests on CI.
2. Disable FUZZING build and testing on Seahorn and KLEE CIs.
> CI: Fix KLEE failing tests for malloc_havoc

- .github/workflows/blacklist.vac.txt
- seahorn/CMakeLists.txt
- seahorn/include/proof_allocators.h
- seahorn/jobs_unsafe/mem_realloc_unsafe/CMakeLists.txt
- seahorn/jobs_unsafe/mem_realloc_unsafe/aws_mem_realloc_unsafe_harness.c
- seahorn/lib/proof_allocators.c
This PR includes a simple unsafe test for a bug we found on the `aws_mem_realloc` function: 
https://github.com/awslabs/aws-c-common/blob/5fa4275653600b66cdbfee8fcf407eb4416f6b18/source/allocator.c#L217
- Bug descriptions.
`aws_mem_realloc` could failed on calling `mem_cpy`:
https://github.com/awslabs/aws-c-common/blob/5fa4275653600b66cdbfee8fcf407eb4416f6b18/source/allocator.c#L245
Because the `*ptr` could be a `NULL` and the `oldsize > 0`.
- Why this is a bug?
Since there are no preconditions for the `void **ptr` and size `oldsize`. The `*ptr` could be a `NULL` and the `oldsize > 0`.
Another precondition is when there is no mem realloc in the aws allocator (realloc is an optional):
https://github.com/awslabs/aws-c-common/blob/5fa4275653600b66cdbfee8fcf407eb4416f6b18/include/aws/common/al …
> Unsafe job for aws mem realloc

- docker/verify-c-common.Dockerfile
The rm commands do not work since aws-c-common is not owned. This has been undetected because this directory does not exist in a fresh client. Also remove build dir if it exists.
> fix(docker): make usea owner

- README.md
Set main version of LLVM to 14
Noted that KLEE uses LLVM 11, SMACK uses 12, Symbiotic uses 10
> fix: updated LLVM version in README
